version: '3'

services:

  db:
    image: quay.io/azavea/postgis:2.4-postgres10.3-slim
    ports:
      - "5432"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
    volumes:
      - .:/opt/grout
    environment:
      - PYTHONUNBUFFERED=0  # Do not buffer output (allows Docker to stream stdout)

  makemigrations:
    build:
      context: .
      dockerfile: Dockerfile.makemigrations
    volumes:
      - .:/opt/grout
    environment:
      - DJANGO_SETTINGS_MODULE=grout.settings_migrations
    command:
      - django-admin makemigrations
