version: '3'

services:

  db:
    image: quay.io/azavea/postgis:2.4-postgres10.3-slim
    ports:
      - "5432"

  py27:
    build:
      context: .
      dockerfile: Dockerfile.py27
    depends_on:
      - db
    volumes:
      - .:/opt/grout

  py34:
    build:
      context: .
      dockerfile: Dockerfile.py34
    depends_on:
      - db
    volumes:
      - .:/opt/grout

  py35:
    build:
      context: .
      dockerfile: Dockerfile.py35
    depends_on:
      - db
    volumes:
      - .:/opt/grout

  py36:
    build:
      context: .
      dockerfile: Dockerfile.py36
    depends_on:
      - db
    volumes:
      - .:/opt/grout

  py37:
    build:
      context: .
      dockerfile: Dockerfile.py37
    depends_on:
      - db
    volumes:
      - .:/opt/grout

  django-admin:
    build:
      context: .
      dockerfile: Dockerfile.py37
    depends_on:
      - db
    volumes:
      - .:/opt/grout
    environment:
      - DJANGO_SETTINGS_MODULE=grout.settings_mgmt
    entrypoint:
      - django-admin
