version: '3'

services:

  db:
    image: quay.io/azavea/postgis:2.4-postgres10.3-slim
    ports:
      - "5432"

  test:
    build: .
    depends_on:
      - db
    volumes:
      - .:/opt/ashlar
    environment:
      - PYTHONUNBUFFERED=0  # Do not buffer output (allows Docker to stream stdout)
