---

- name: Add root_py_dir to pythonpath
  lineinfile: dest=/etc/environment
              line="PYTHONPATH={{ root_py_dir }}:$PYTHONPATH"

- name: Install python requirements
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    # TODO: Upgrade to 1.0 when released
    # 4/14/2015 - From the SQLAlchemy 1.0.0b5 changelog:
    # "At this point, 1.0.0 is ready to go and should be released very soon."
    - { name: 'SQLAlchemy', version: '0.9.9' }
    - { name: 'GeoAlchemy2', version: '0.2.4' }
    - { name: 'Flask', version: '0.10.1' }
    - { name: 'Flask-SQLAlchemy', version: '2.0' }
    - { name: 'flask-restful', version: '0.3.2' }
    - { name: 'Flask-Restless', version: '0.17.0' }
    - { name: 'alembic', version: '0.7.4' }
    - { name: 'jsonschema', version: '2.4.0' }
  notify: Restart ashlar

- name: Install python dev requirements
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - { name: 'ipython', version: '3.0.0' }
    - { name: 'ipdb', version: '0.8' }
  when: developing
  notify: Restart ashlar

- name: Install Alembic config
  template: src=alembic.ini.j2 dest={{ root_py_dir }}/alembic.ini

- name: Run migrations
  command: alembic upgrade head
  sudo: False
  args:
    chdir: "{{ root_py_dir }}"

- name: Touch log file if it does not exist
  command: touch {{ app_log }}
           creates={{ app_log }}

- name: Set log file permissions
  file: path={{ app_log }} owner={{ app_username }} group={{ app_username }} mode=0664

- name: Create configuration file directory
  file: path={{ root_conf_dir }}
        owner={{ app_username }}
        group={{ app_username }}
        mode=0750
        state=directory

- name: Configure gunicorn
  template: src=gunicorn-ashlar.py.j2 dest={{ root_conf_dir }}/gunicorn.py
  notify: Restart ashlar

- name: Configure service definition
  template: src=upstart-ashlar.conf.j2 dest=/etc/init/ashlar.conf
  notify: Restart ashlar

- name: Copy app configuration
  template: src=app-config.py.j2 dest={{ root_app_dir }}/config.py
  notify: Restart ashlar

- name: Copy nginx config
  template: src=nginx-default.j2 dest=/etc/nginx/sites-available/default
  notify: Restart nginx
