---

- name: Create app directory
  file: path={{ ashlar_app_dir }}
        owner={{ ashlar_user }}
        group={{ ashlar_user }}
        mode=0775
        state=directory

- name: Install python requirements
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    # TODO: Upgrade to 1.0 when released
    # 4/14/2015 - From the SQLAlchemy 1.0.0b5 changelog:
    # "At this point, 1.0.0 is ready to go and should be released very soon."
    - { name: 'SQLAlchemy', version: '0.9.9' }
    - { name: 'Flask', version: '0.10.1' }
    - { name: 'Flask-SQLAlchemy', version: '2.0' }
  notify: Restart gunicorn

- name: Install python dev requirements
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - { name: 'ipython', version: '3.0.0' }
    - { name: 'ipdb', version: '0.8' }
  notify: Restart gunicorn
  when: developing
