---

# Installs packages/dependencies for database servers

- hosts: database-servers

  sudo: yes

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "ashlar.database" }
